use midenc_frontend_wasm_metadata::FrontendMetadata;
use proc_macro2::{Literal, Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{FnArg, ItemFn, Type, parse_macro_input, spanned::Spanned};

use crate::{
    boilerplate::runtime_boilerplate,
    util::{generate_frontend_link_section, is_type_named, is_unit_return_type},
    wit_builder::WitBuilder,
    wit_world::{ManifestPackage, write_world_block},
};

/// Name of the entrypoint function exported by the transaction-script WIT interface.
const EXPORT_NAME: &str = "run";

/// Configuration describing the script macro expansion details.
pub(crate) struct ScriptConfig {
    /// Fully-qualified export interface emitted by the generated WIT world.
    pub export_interface: &'static str,
    /// Fully-qualified path to the guest trait implemented by the generated struct.
    pub guest_trait_path: &'static str,
}

/// Configuration for generating a script guest wrapper.
pub(crate) struct GuestWrapperConfig {
    /// Fully-qualified export interface emitted by the generated WIT world.
    pub export_interface: &'static str,
    /// Fully-qualified path to the guest trait implemented by the generated struct.
    pub guest_trait_path: &'static str,
    /// The name of the generated guest struct.
    pub guest_struct_ident: syn::Ident,
    /// Doc string attached to the generated guest struct.
    pub guest_struct_doc: &'static str,
}

/// Generates the shared script wrapper boilerplate (WIT bindings + export glue + guest entrypoint).
///
/// The guest entrypoint receives the `TX_SCRIPT_ARGS` word as `arg`; `run_body` may reference it.
pub(crate) fn expand_guest_wrapper(
    error_span: Span,
    config: GuestWrapperConfig,
    user_items: TokenStream2,
    trait_impls: TokenStream2,
    run_body: TokenStream2,
) -> syn::Result<TokenStream2> {
    let inline_wit = build_script_wit(error_span, config.export_interface)?;
    let inline_literal = Literal::string(&inline_wit);

    let export_path: syn::Path = syn::parse_str(config.guest_trait_path).map_err(|err| {
        syn::Error::new(
            error_span,
            format!("failed to parse guest trait path '{}': {err}", config.guest_trait_path),
        )
    })?;

    let runtime_boilerplate = runtime_boilerplate();
    let guest_struct_ident = config.guest_struct_ident;
    let doc = config.guest_struct_doc;
    let export_ident = quote::format_ident!("{EXPORT_NAME}");

    Ok(quote! {
        #runtime_boilerplate

        #user_items

        ::miden::generate!(inline = #inline_literal);
        self::bindings::export!(#guest_struct_ident);

        #trait_impls

        // Bring ActiveAccount trait into scope so users can call account.get_id(), etc.
        #[allow(unused_imports)]
        use ::miden::active_account::ActiveAccount as _;

        #[doc = #doc]
        pub struct #guest_struct_ident;

        impl #export_path for #guest_struct_ident {
            fn #export_ident(arg: ::miden::Word) {
                #run_body
            }
        }
    })
}

/// Expansion logic used by `#[tx_script]`.
pub(crate) fn expand(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
    config: ScriptConfig,
) -> proc_macro::TokenStream {
    if !attr.is_empty() {
        return syn::Error::new(Span::call_site(), "this attribute does not accept arguments")
            .into_compile_error()
            .into();
    }

    let input_fn = parse_macro_input!(item as ItemFn);

    let params = match parse_entrypoint_signature(&input_fn) {
        Ok(params) => params,
        Err(err) => return err.into_compile_error().into(),
    };

    let fn_ident = &input_fn.sig.ident;
    let struct_ident = quote::format_ident!("Struct");

    // Instantiate each declared parameter and call the user's function with them in declared
    // order. The script-args parameter is decoded from the `TX_SCRIPT_ARGS` word through the
    // `ScriptArgs` trait; the account parameter is instantiated through the `AccountWrapper`
    // marker trait, which is implemented by `#[account(...)]`: this binds the parameter to the
    // active account and rejects types not generated by that macro with a trait-bound error.
    let mut instantiation = TokenStream2::new();
    let mut call_args = Vec::new();
    for param in &params {
        match param {
            ParamRole::Args(ty) => {
                instantiation.extend(quote! {
                    let __miden_args = <#ty as ::miden::ScriptArgs>::decode(arg);
                });
                call_args.push(quote! { __miden_args });
            }
            ParamRole::Account { ty, mut_ref: true } => {
                instantiation.extend(quote! {
                    let mut __miden_account =
                        <#ty as ::miden::active_account::AccountWrapper>::active();
                });
                call_args.push(quote! { &mut __miden_account });
            }
            ParamRole::Account { ty, mut_ref: false } => {
                instantiation.extend(quote! {
                    let __miden_account =
                        <#ty as ::miden::active_account::AccountWrapper>::active();
                });
                call_args.push(quote! { &__miden_account });
            }
        }
    }

    // Mark the generated entrypoint export so downstream consumers can identify the
    // transaction-script procedure by its `@transaction_script` attribute (e.g.
    // `TransactionScript::from_library` in `miden-protocol`). The export name is fixed by the
    // transaction-script WIT interface regardless of the user's function name.
    let frontend_link_section = generate_frontend_link_section(&[FrontendMetadata::TxScript {
        method_path: fn_ident.to_string(),
        export_name: EXPORT_NAME.to_string(),
    }]);

    let expanded = match expand_guest_wrapper(
        Span::call_site(),
        GuestWrapperConfig {
            export_interface: config.export_interface,
            guest_trait_path: config.guest_trait_path,
            guest_struct_ident: struct_ident.clone(),
            guest_struct_doc: "Guest entry point generated by the Miden script attribute.",
        },
        quote! { #input_fn },
        quote! { #frontend_link_section },
        quote! {
            #instantiation
            #fn_ident(#(#call_args),*);
        },
    ) {
        Ok(tokens) => tokens,
        Err(err) => err.into_compile_error(),
    };

    expanded.into()
}

/// Role of an entrypoint parameter, in declaration order.
enum ParamRole {
    /// By-value script-args parameter, decoded from the `TX_SCRIPT_ARGS` word.
    Args(Type),
    /// Reference to an `#[account(...)]` type bound to the active account.
    Account { ty: Type, mut_ref: bool },
}

/// Parses and validates the entrypoint signature, returning the parameter roles in declaration
/// order.
///
/// The entrypoint must be a free function returning `()`, accepting 1 or 2 parameters (in any
/// order):
/// - one by-value parameter holding the script arguments (a type implementing `ScriptArgs`), and
/// - optionally one reference to an `#[account(...)]` type (`&MyAccount` or `&mut MyAccount`).
fn parse_entrypoint_signature(input_fn: &ItemFn) -> syn::Result<Vec<ParamRole>> {
    let sig = &input_fn.sig;

    if sig.receiver().is_some() {
        return Err(syn::Error::new(sig.span(), "this attribute cannot target methods"));
    }

    if let Some(asyncness) = sig.asyncness {
        return Err(syn::Error::new(asyncness.span(), "entrypoint must not be `async`"));
    }

    if !sig.generics.params.is_empty() || sig.generics.where_clause.is_some() {
        return Err(syn::Error::new(sig.generics.span(), "entrypoint must not be generic"));
    }

    if !is_unit_return_type(&sig.output) {
        return Err(syn::Error::new(sig.output.span(), "entrypoint must return `()`"));
    }

    if sig.inputs.len() > 2 {
        return Err(syn::Error::new(
            sig.span(),
            "entrypoint accepts 1 or 2 parameters: a by-value script-args value and an optional \
             reference to an `#[account(...)]` type",
        ));
    }

    let mut params = Vec::new();
    for arg in &sig.inputs {
        let FnArg::Typed(pat_type) = arg else {
            unreachable!("receiver arguments are rejected before parameter classification");
        };
        let param = classify_param(pat_type.ty.as_ref())?;

        match &param {
            ParamRole::Args(_)
                if params.iter().any(|other| matches!(other, ParamRole::Args(_))) =>
            {
                return Err(syn::Error::new(
                    pat_type.ty.span(),
                    "entrypoint may only declare a single script-args parameter",
                ));
            }
            ParamRole::Account { .. }
                if params.iter().any(|other| matches!(other, ParamRole::Account { .. })) =>
            {
                return Err(syn::Error::new(
                    pat_type.ty.span(),
                    "entrypoint may only declare a single account parameter",
                ));
            }
            _ => params.push(param),
        }
    }

    if !params.iter().any(|param| matches!(param, ParamRole::Args(_))) {
        return Err(syn::Error::new(
            sig.span(),
            "entrypoint must declare a by-value script-args parameter (a type implementing \
             `ScriptArgs`, e.g. `arg: Word`)",
        ));
    }

    Ok(params)
}

/// Classifies an entrypoint parameter type as script-args or account.
fn classify_param(ty: &Type) -> syn::Result<ParamRole> {
    const EXPECTED: &str = "unsupported entrypoint parameter type; expected a by-value \
                            script-args value (a type implementing `ScriptArgs`) or a reference \
                            to an `#[account(...)]` type (e.g. `account: &mut MyAccount`)";

    match ty {
        // Any reference to a concrete path type other than `Word` is treated as the account
        // parameter; whether it really is an account wrapper is enforced by the `AccountWrapper`
        // bound. `&Word` is rejected: the args word is passed by value.
        Type::Reference(type_ref) => {
            if !matches!(type_ref.elem.as_ref(), Type::Path(_))
                || is_type_named(&type_ref.elem, "Word")
            {
                return Err(syn::Error::new(ty.span(), EXPECTED));
            }
            Ok(ParamRole::Account {
                ty: (*type_ref.elem).clone(),
                mut_ref: type_ref.mutability.is_some(),
            })
        }
        // Any by-value path type is the script-args parameter; whether it can be decoded is
        // enforced by the `ScriptArgs` bound.
        Type::Path(_) => Ok(ParamRole::Args(ty.clone())),
        other => Err(syn::Error::new(other.span(), EXPECTED)),
    }
}

/// Builds an inlined WIT world definition for a script crate.
pub(crate) fn build_script_wit(
    error_span: Span,
    export_interface: &'static str,
) -> Result<String, syn::Error> {
    let manifest = ManifestPackage::load(error_span)?;
    let crate_name = manifest.crate_name(error_span)?;
    let component_package = manifest.component_package();
    let component_version = manifest.component_version();
    let imports = manifest.collect_miden_dependency_imports(error_span)?;
    let world_name = format!("{}-world", crate_name.replace('_', "-"));
    let exports = [export_interface.to_string()];

    let mut wit = WitBuilder::new("#[tx_script]", &component_package, component_version);
    write_world_block(&mut wit, &world_name, &imports, &exports);

    Ok(wit.finish())
}

#[cfg(test)]
mod tests {
    use syn::parse_quote;

    use super::*;

    fn roles(input_fn: &ItemFn) -> Vec<ParamRole> {
        match parse_entrypoint_signature(input_fn) {
            Ok(params) => params,
            Err(err) => panic!("expected signature validation to succeed: {err}"),
        }
    }

    fn expect_err(input_fn: &ItemFn) -> syn::Error {
        match parse_entrypoint_signature(input_fn) {
            Ok(_) => panic!("expected signature validation to fail"),
            Err(err) => err,
        }
    }

    #[test]
    fn signature_accepts_args_and_mutable_account() {
        let input_fn: ItemFn = parse_quote! {
            fn run(inputs: TxScriptArg, account: &mut BasicWallet) {}
        };

        let params = roles(&input_fn);
        assert!(matches!(params[0], ParamRole::Args(_)));
        assert!(matches!(params[1], ParamRole::Account { mut_ref: true, .. }));
    }

    #[test]
    fn signature_accepts_account_before_args() {
        let input_fn: ItemFn = parse_quote! {
            fn run(account: &BasicWallet, inputs: TxScriptArg) {}
        };

        let params = roles(&input_fn);
        assert!(matches!(params[0], ParamRole::Account { mut_ref: false, .. }));
        assert!(matches!(params[1], ParamRole::Args(_)));
    }

    #[test]
    fn signature_rejects_no_parameters() {
        let input_fn: ItemFn = parse_quote! {
            fn run() {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("must declare a by-value script-args parameter"));
    }

    #[test]
    fn signature_rejects_account_only() {
        let input_fn: ItemFn = parse_quote! {
            fn run(account: &mut BasicWallet) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("must declare a by-value script-args parameter"));
    }

    #[test]
    fn signature_accepts_word_args() {
        // `Word` implements `ScriptArgs`, so the pre-redesign raw-word signature keeps working.
        let input_fn: ItemFn = parse_quote! {
            fn run(arg: Word, account: &mut BasicWallet) {}
        };

        let params = roles(&input_fn);
        assert!(matches!(params[0], ParamRole::Args(_)));
    }

    #[test]
    fn signature_accepts_non_run_name() {
        let input_fn: ItemFn = parse_quote! {
            fn transfer(inputs: TxScriptArg) {}
        };

        assert_eq!(roles(&input_fn).len(), 1);
    }

    #[test]
    fn signature_accepts_account_named_wrapper_type() {
        // A user-defined `#[account(...)]` struct may be named `Account`; whether the type
        // really is an account wrapper is enforced by the `AccountWrapper` bound, not by name.
        let input_fn: ItemFn = parse_quote! {
            fn run(arg: Word, account: &mut Account) {}
        };

        assert!(parse_entrypoint_signature(&input_fn).is_ok());
    }

    #[test]
    fn signature_rejects_two_args_parameters() {
        let input_fn: ItemFn = parse_quote! {
            fn run(a: FirstArgs, b: SecondArgs) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("single script-args parameter"));
    }

    #[test]
    fn signature_rejects_two_account_parameters() {
        let input_fn: ItemFn = parse_quote! {
            fn run(a: &mut Wallet, b: &Faucet) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("single account parameter"));
    }

    #[test]
    fn signature_rejects_word_reference() {
        let input_fn: ItemFn = parse_quote! {
            fn run(arg: &Word) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("unsupported entrypoint parameter type"));
    }

    #[test]
    fn signature_rejects_three_parameters() {
        let input_fn: ItemFn = parse_quote! {
            fn run(a: TxScriptArg, b: &mut Wallet, c: Word) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("1 or 2 parameters"));
    }

    #[test]
    fn signature_rejects_receiver() {
        let input_fn: ItemFn = parse_quote! {
            fn run(&self) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("cannot target methods"));
    }

    #[test]
    fn signature_rejects_async() {
        let input_fn: ItemFn = parse_quote! {
            async fn run() {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("must not be `async`"));
    }

    #[test]
    fn signature_rejects_generics() {
        let input_fn: ItemFn = parse_quote! {
            fn run<T>(inputs: T) {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("must not be generic"));
    }

    #[test]
    fn signature_rejects_non_unit_return() {
        let input_fn: ItemFn = parse_quote! {
            fn run() -> Word {}
        };

        let err = expect_err(&input_fn);
        assert!(err.to_string().contains("must return `()`"));
    }
}
