use midenc_frontend_wasm_metadata::FrontendMetadata;
use proc_macro2::{Literal, Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{FnArg, ItemFn, Pat, PatIdent, parse_macro_input, spanned::Spanned};

use crate::{
    boilerplate::runtime_boilerplate,
    util::generate_frontend_link_section,
    wit_builder::WitBuilder,
    wit_world::{ManifestPackage, write_world_block},
};

/// Configuration describing the script macro expansion details.
pub(crate) struct ScriptConfig {
    /// Fully-qualified export interface emitted by the generated WIT world.
    pub export_interface: &'static str,
    /// Fully-qualified path to the guest trait implemented by the generated struct.
    pub guest_trait_path: &'static str,
}

/// Configuration for generating a script guest wrapper.
pub(crate) struct GuestWrapperConfig {
    /// Fully-qualified export interface emitted by the generated WIT world.
    pub export_interface: &'static str,
    /// Fully-qualified path to the guest trait implemented by the generated struct.
    pub guest_trait_path: &'static str,
    /// The name of the generated guest struct.
    pub guest_struct_ident: syn::Ident,
    /// Doc string attached to the generated guest struct.
    pub guest_struct_doc: &'static str,
}

/// Generates the shared script wrapper boilerplate (WIT bindings + export glue + guest entrypoint).
pub(crate) fn expand_guest_wrapper(
    error_span: Span,
    config: GuestWrapperConfig,
    user_items: TokenStream2,
    trait_impls: TokenStream2,
    run_body: TokenStream2,
) -> syn::Result<TokenStream2> {
    let inline_wit = build_script_wit(error_span, config.export_interface)?;
    let inline_literal = Literal::string(&inline_wit);

    let export_path: syn::Path = syn::parse_str(config.guest_trait_path).map_err(|err| {
        syn::Error::new(
            error_span,
            format!("failed to parse guest trait path '{}': {err}", config.guest_trait_path),
        )
    })?;

    let runtime_boilerplate = runtime_boilerplate();
    let guest_struct_ident = config.guest_struct_ident;
    let doc = config.guest_struct_doc;

    Ok(quote! {
        #runtime_boilerplate

        #user_items

        ::miden::generate!(inline = #inline_literal);
        self::bindings::export!(#guest_struct_ident);

        #trait_impls

        // Bring ActiveAccount trait into scope so users can call account.get_id(), etc.
        #[allow(unused_imports)]
        use ::miden::active_account::ActiveAccount as _;

        #[doc = #doc]
        pub struct #guest_struct_ident;

        impl #export_path for #guest_struct_ident {
            fn run(arg: ::miden::Word) {
                #run_body
            }
        }
    })
}

/// Expansion logic used by `#[tx_script]`.
pub(crate) fn expand(
    attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
    config: ScriptConfig,
) -> proc_macro::TokenStream {
    if !attr.is_empty() {
        return syn::Error::new(Span::call_site(), "this attribute does not accept arguments")
            .into_compile_error()
            .into();
    }

    let input_fn = parse_macro_input!(item as ItemFn);

    let fn_ident = &input_fn.sig.ident;
    if fn_ident != "run" {
        return syn::Error::new(fn_ident.span(), "this attribute must be applied to `fn run`")
            .into_compile_error()
            .into();
    }

    if input_fn.sig.receiver().is_some() {
        return syn::Error::new(input_fn.sig.span(), "this attribute cannot target methods")
            .into_compile_error()
            .into();
    }

    // Parse the optional second parameter (injected wrapper struct).
    // The trait requires `fn run(arg: Word)`, so if the user declares a second parameter,
    // it will be instantiated via `AccountWrapper::active()` and passed to the user's function.
    let injected_param = match parse_injected_param(&input_fn) {
        Ok(param) => param,
        Err(err) => return err.into_compile_error().into(),
    };

    let struct_ident = quote::format_ident!("Struct");

    // Generate the call to the user's function, with optional injected parameter. The injected
    // account parameter is instantiated through the `AccountWrapper` marker trait, which is
    // implemented by `#[account(...)]`: this binds the parameter to the active account
    // and rejects types not generated by that macro with a trait-bound error.
    let (instantiation, call) = match &injected_param {
        Some((ident, ty, mut_ref)) => (
            if *mut_ref {
                quote! {
                    let mut #ident = <#ty as ::miden::active_account::AccountWrapper>::active();
                }
            } else {
                quote! {
                    let #ident = <#ty as ::miden::active_account::AccountWrapper>::active();
                }
            },
            if *mut_ref {
                quote! { #fn_ident(arg, &mut #ident) }
            } else {
                quote! { #fn_ident(arg, &#ident) }
            },
        ),
        None => (quote! {}, quote! { #fn_ident(arg) }),
    };

    // Mark the generated entrypoint export so downstream consumers can identify the
    // transaction-script procedure by its `@transaction_script` attribute (e.g.
    // `TransactionScript::from_library` in `miden-protocol`).
    let frontend_link_section = generate_frontend_link_section(&[FrontendMetadata::TxScript {
        method_path: fn_ident.to_string(),
        export_name: fn_ident.to_string(),
    }]);

    let expanded = match expand_guest_wrapper(
        Span::call_site(),
        GuestWrapperConfig {
            export_interface: config.export_interface,
            guest_trait_path: config.guest_trait_path,
            guest_struct_ident: struct_ident.clone(),
            guest_struct_doc: "Guest entry point generated by the Miden script attribute.",
        },
        quote! { #input_fn },
        quote! { #frontend_link_section },
        quote! {
            #instantiation
            #call;
        },
    ) {
        Ok(tokens) => tokens,
        Err(err) => err.into_compile_error(),
    };

    expanded.into()
}

/// Parses the optional injected parameter from the user's `fn run` signature.
///
/// The trait requires `fn run(arg: Word)`. If the user declares a second parameter,
/// it is treated as an "injected" wrapper struct that will be instantiated via
/// `AccountWrapper::active()` and passed to the user's function.
///
/// Only up to 2 parameters are supported: `(arg: Word)` or `(arg: Word, account: &mut MyAccount)`
/// where `MyAccount` is an `#[account(...)]` type (`&MyAccount` is accepted as well).
///
/// Returns `Some((ident, type, is_mut_ref))` if a second parameter exists, `None` otherwise.
fn parse_injected_param(input_fn: &ItemFn) -> syn::Result<Option<(syn::Ident, syn::Type, bool)>> {
    if input_fn.sig.inputs.is_empty() {
        return Err(syn::Error::new(
            input_fn.sig.span(),
            "fn run requires at least one parameter: (arg: Word) or (arg: Word, account: &mut \
             MyAccount) where `MyAccount` is an `#[account(...)]` type",
        ));
    }

    if input_fn.sig.inputs.len() > 2 {
        return Err(syn::Error::new(
            input_fn.sig.span(),
            "fn run accepts at most 2 parameters: (arg: Word) or (arg: Word, account: &mut \
             MyAccount) where `MyAccount` is an `#[account(...)]` type",
        ));
    }

    // Validate the first parameter is `arg: Word`
    let first_arg = input_fn.sig.inputs.first().unwrap();
    match first_arg {
        FnArg::Typed(pat_type) => {
            if !matches!(pat_type.pat.as_ref(), Pat::Ident(_)) {
                return Err(syn::Error::new(
                    pat_type.pat.span(),
                    "first parameter must be a simple identifier (e.g., `arg: Word`)",
                ));
            }
            // Check that the type is `Word`
            if !is_type_named(&pat_type.ty, "Word") {
                return Err(syn::Error::new(
                    pat_type.ty.span(),
                    "first parameter must have type `Word` (e.g., `arg: Word`)",
                ));
            }
        }
        FnArg::Receiver(receiver) => {
            return Err(syn::Error::new(receiver.span(), "unexpected receiver argument"));
        }
    }

    let Some(second_arg) = input_fn.sig.inputs.iter().nth(1) else {
        return Ok(None);
    };

    match second_arg {
        FnArg::Typed(pat_type) => {
            let ident = match pat_type.pat.as_ref() {
                Pat::Ident(PatIdent { ident, .. }) => ident.clone(),
                other => {
                    return Err(syn::Error::new(
                        other.span(),
                        "function arguments must be simple identifiers",
                    ));
                }
            };
            let (ty, mut_ref) = expect_account_ref_type(&pat_type.ty)?;
            Ok(Some((ident, ty, mut_ref)))
        }
        FnArg::Receiver(receiver) => {
            Err(syn::Error::new(receiver.span(), "unexpected receiver argument"))
        }
    }
}

/// Ensures the type is a reference to an `#[account(...)]` type (any concrete path type other
/// than `Word`) and returns the underlying account type along with the reference mutability.
///
/// The generated glue instantiates the type through the `AccountWrapper` trait, so types not
/// generated by `#[account(...)]` are rejected by the trait bound.
fn expect_account_ref_type(ty: &syn::Type) -> syn::Result<(syn::Type, bool)> {
    const EXPECTED: &str = "second parameter must be a reference to an `#[account(...)]` type \
                            (e.g. `account: &mut MyAccount`)";

    let syn::Type::Reference(type_ref) = ty else {
        return Err(syn::Error::new(ty.span(), EXPECTED));
    };
    if !matches!(type_ref.elem.as_ref(), syn::Type::Path(_))
        || is_type_named(&type_ref.elem, "Word")
    {
        return Err(syn::Error::new(ty.span(), EXPECTED));
    }
    Ok(((*type_ref.elem).clone(), type_ref.mutability.is_some()))
}

/// Checks if a type's final path segment matches `name` (allowing module-qualified paths like
/// `miden::Word`).
fn is_type_named(ty: &syn::Type, name: &str) -> bool {
    let syn::Type::Path(type_path) = ty else {
        return false;
    };
    if type_path.qself.is_some() {
        return false;
    }
    type_path
        .path
        .segments
        .last()
        .is_some_and(|seg| seg.ident == name && seg.arguments.is_empty())
}

/// Builds an inlined WIT world definition for a script crate.
pub(crate) fn build_script_wit(
    error_span: Span,
    export_interface: &'static str,
) -> Result<String, syn::Error> {
    let manifest = ManifestPackage::load(error_span)?;
    let crate_name = manifest.crate_name(error_span)?;
    let component_package = manifest.component_package();
    let component_version = manifest.component_version();
    let imports = manifest.collect_miden_dependency_imports(error_span)?;
    let world_name = format!("{}-world", crate_name.replace('_', "-"));
    let exports = [export_interface.to_string()];

    let mut wit = WitBuilder::new("#[tx_script]", &component_package, component_version);
    write_world_block(&mut wit, &world_name, &imports, &exports);

    Ok(wit.finish())
}

#[cfg(test)]
mod tests {
    use syn::parse_quote;

    use super::*;

    #[test]
    fn run_signature_accepts_account_wrapper_reference() {
        let input_fn: ItemFn = parse_quote! {
            fn run(arg: Word, account: &mut BasicWallet) {}
        };

        let (_, _, mut_ref) = parse_injected_param(&input_fn).unwrap().unwrap();
        assert!(mut_ref);
    }

    #[test]
    fn run_signature_accepts_shared_account_wrapper_reference() {
        let input_fn: ItemFn = parse_quote! {
            fn run(arg: Word, account: &BasicWallet) {}
        };

        let (_, _, mut_ref) = parse_injected_param(&input_fn).unwrap().unwrap();
        assert!(!mut_ref);
    }

    #[test]
    fn run_signature_accepts_account_named_wrapper_type() {
        // A user-defined `#[account(...)]` struct may be named `Account`; whether the type
        // really is an account wrapper is enforced by the `AccountWrapper` bound, not by name.
        let input_fn: ItemFn = parse_quote! {
            fn run(arg: Word, account: &mut Account) {}
        };

        assert!(parse_injected_param(&input_fn).is_ok());
    }
}
