//! Shared encoding for frontend-only Wasm metadata emitted by SDK macros.

#![deny(warnings)]
#![deny(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]
#![no_std]

extern crate alloc;

use alloc::{string::String, vec::Vec};

use serde::{Deserialize, Serialize};

/// Name of the Wasm custom section used to store frontend metadata bytes.
pub const WASM_FRONTEND_METADATA_CUSTOM_SECTION_NAME: &str =
    "rodata,miden_account_component_frontend";

/// Frontend-only metadata emitted by the SDK macros into a dedicated Wasm custom section.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum FrontendMetadata {
    /// Metadata for the single export marked with `#[auth_script]`.
    AuthScript {
        /// Fully-qualified Rust method path marked with `#[auth_script]`.
        method_path: String,
        /// Name of the export marked with `#[auth_script]`.
        export_name: String,
    },
    /// Metadata for an export marked with `#[account_procedure]`.
    AccountProcedure {
        /// Fully-qualified Rust method path marked with `#[account_procedure]`.
        method_path: String,
        /// Name of the export marked with `#[account_procedure]`.
        export_name: String,
    },
    /// Metadata for the single export marked with `#[note_script]`.
    NoteScript {
        /// Fully-qualified Rust method path marked with `#[note_script]`.
        method_path: String,
        /// Name of the export marked with `#[note_script]`.
        export_name: String,
    },
    /// Metadata for the single entrypoint generated by `#[tx_script]`.
    TxScript {
        /// Fully-qualified Rust function path marked with `#[tx_script]`.
        method_path: String,
        /// Name of the export generated by `#[tx_script]`.
        export_name: String,
    },
}

/// Semantic kind of a protocol export selected by frontend metadata.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProtocolExportKind {
    /// The export is the component's authentication procedure.
    AuthScript,
    /// The export is one of the component's account-interface procedures.
    AccountProcedure,
    /// The export is the component's note-script entrypoint.
    NoteScript,
    /// The export is the transaction-script entrypoint.
    TxScript,
}

impl FrontendMetadata {
    /// Returns the semantic kind of protocol export selected by this metadata entry.
    pub fn protocol_export_kind(&self) -> ProtocolExportKind {
        match self {
            Self::AuthScript { .. } => ProtocolExportKind::AuthScript,
            Self::AccountProcedure { .. } => ProtocolExportKind::AccountProcedure,
            Self::NoteScript { .. } => ProtocolExportKind::NoteScript,
            Self::TxScript { .. } => ProtocolExportKind::TxScript,
        }
    }

    /// Returns the selected protocol-export kind when `export_name` matches the marked export.
    pub fn protocol_export_kind_for(&self, export_name: &str) -> Option<ProtocolExportKind> {
        (self.export_name() == export_name).then(|| self.protocol_export_kind())
    }

    /// Returns the Rust method path marked by this metadata entry.
    pub fn method_path(&self) -> &str {
        match self {
            Self::AuthScript { method_path, .. }
            | Self::AccountProcedure { method_path, .. }
            | Self::NoteScript { method_path, .. }
            | Self::TxScript { method_path, .. } => method_path,
        }
    }

    /// Returns the export name marked by this metadata entry.
    pub fn export_name(&self) -> &str {
        match self {
            Self::AuthScript { export_name, .. }
            | Self::AccountProcedure { export_name, .. }
            | Self::NoteScript { export_name, .. }
            | Self::TxScript { export_name, .. } => export_name,
        }
    }
}

/// Encodes a set of frontend metadata entries into the bytes stored in the frontend metadata custom
/// section. A component may carry several entries (e.g. an optional `#[auth_script]` entry plus one
/// entry per `#[account_procedure]` method), so the section payload is a list.
pub fn encode_section(entries: &[FrontendMetadata]) -> Result<Vec<u8>, FrontendMetadataError> {
    serde_json::to_vec(entries)
}

/// Decodes the frontend metadata entries stored in the frontend metadata custom section.
pub fn decode_section(bytes: &[u8]) -> Result<Vec<FrontendMetadata>, FrontendMetadataError> {
    serde_json::from_slice(bytes)
}

/// Errors that can occur while encoding or decoding frontend metadata bytes.
pub type FrontendMetadataError = serde_json::Error;

#[cfg(test)]
mod tests {
    use alloc::string::ToString;

    use super::*;

    /// Ensures the shared encoder and decoder remain synchronized for the metadata payload format.
    #[test]
    fn frontend_metadata_roundtrips_payload() {
        let entries = [
            FrontendMetadata::AuthScript {
                method_path: "crate::auth::AuthComponent::authenticate".to_string(),
                export_name: "auth".to_string(),
            },
            FrontendMetadata::NoteScript {
                method_path: "crate::notes::PaymentNote::execute".to_string(),
                export_name: "note-script".to_string(),
            },
        ];

        for entry in entries {
            let entry = alloc::vec![entry];
            let bytes = encode_section(&entry).unwrap();

            assert_eq!(decode_section(&bytes).unwrap(), entry);
        }
    }

    /// Ensures a section carrying several `#[account_procedure]` entries round-trips through the
    /// section encoder and decoder.
    #[test]
    fn frontend_metadata_section_roundtrips_multiple_account_procedures() {
        let entries = alloc::vec![
            FrontendMetadata::AccountProcedure {
                method_path: "crate::wallet::BasicWallet::receive_asset".to_string(),
                export_name: "receive-asset".to_string(),
            },
            FrontendMetadata::AccountProcedure {
                method_path: "crate::wallet::BasicWallet::move_asset_to_note".to_string(),
                export_name: "move-asset-to-note".to_string(),
            },
            FrontendMetadata::AccountProcedure {
                method_path: "crate::wallet::BasicWallet::create_note".to_string(),
                export_name: "create-note".to_string(),
            },
        ];

        let bytes = encode_section(&entries).unwrap();

        assert_eq!(decode_section(&bytes).unwrap(), entries);
    }

    /// Ensures protocol-export matching preserves the semantic export kind.
    #[test]
    fn frontend_metadata_matches_protocol_export_kind() {
        let auth_metadata = FrontendMetadata::AuthScript {
            method_path: "crate::auth::AuthComponent::authenticate".to_string(),
            export_name: "auth".to_string(),
        };
        let note_metadata = FrontendMetadata::NoteScript {
            method_path: "crate::notes::PaymentNote::execute".to_string(),
            export_name: "note-script".to_string(),
        };

        assert_eq!(
            auth_metadata.protocol_export_kind_for("auth"),
            Some(ProtocolExportKind::AuthScript)
        );
        assert_eq!(auth_metadata.protocol_export_kind_for("other"), None);
        assert_eq!(
            note_metadata.protocol_export_kind_for("note-script"),
            Some(ProtocolExportKind::NoteScript)
        );
        assert_eq!(note_metadata.protocol_export_kind_for("other"), None);
    }
}
