[package]
name = "auth-component-no-auth"
version = "0.1.0"

[lib]
kind = "account-component"
namespace = "miden:auth-component-no-auth/auth-component@0.1.0"
path = "src/lib.rs"

[dependencies]
miden-core = "*"
miden-protocol = "*"

[package.metadata.miden]
supported-types = ["RegularAccountUpdatableCode"]
