[package]
name = "counter-note"
version = "0.1.0"

[lib]
kind = "note"
namespace = "miden:counter-note/miden-counter-note@0.1.0"
path = "src/lib.rs"

[dependencies]
miden-core = "*"
miden-protocol = "*"
counter-contract = { path = "../counter-contract" }

[package.metadata.miden.dependencies]
counter-contract = { wit = "../counter-contract/target/generated-wit/" }
