[package]
name = "p2id"
version = "0.1.0"

[lib]
kind = "note"
namespace = "miden:p2id/miden-p2id@0.1.0"
path = "src/lib.rs"

[dependencies]
miden-core = "*"
miden-protocol = "*"
basic-wallet = { path = "../basic-wallet" }

[package.metadata.miden.dependencies]
basic-wallet = { wit = "../basic-wallet/target/generated-wit/" }
